version: '3'
services:
  client:
    build: ./client
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    working_dir: /root/client
    volumes:
      - ./client:/root/client:cached

  server:
    image: golang:1.12-alpine
    command: sh -c "go run ."
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    working_dir: /root/server
    volumes:
      - ./server:/root/server:cached