name: mp-open-weather

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup client
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
        working-directory: ./client
      - name: Setup server
        uses: actions/setup-go@v1
        with:
          go-version: '^1.13.1'
      - run: go run main.go
        working-directory: ./server
  
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker-compose build
      - name: Tags
        run: |
          docker tag mp-open-weather_client ${{ secrets.DOCKER_USER }}/mp-open-weather:${{ github.sha }}
          docker tag mp-open-weather_client ${{ secrets.DOCKER_USER }}/mp-open-weather:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/mp-open-weather:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/mp-open-weather:latest

